/** Stable names used while the product moves from kobe to rove. */
import {
  LEGACY_KOBE_CONFIG_DIR_BASENAME,
  LEGACY_KOBE_PRODUCT_NAME,
  LEGACY_KOBE_STATE_DIR_BASENAME,
  ROVE_CONFIG_DIR_BASENAME,
  ROVE_PRODUCT_NAME,
  ROVE_STATE_DIR_BASENAME,
} from "@sma1lboy/kobe-daemon/compat-env"

export {
  LEGACY_KOBE_CONFIG_DIR_BASENAME,
  LEGACY_KOBE_PRODUCT_NAME,
  LEGACY_KOBE_STATE_DIR_BASENAME,
  ROVE_CONFIG_DIR_BASENAME,
  ROVE_PRODUCT_NAME,
  ROVE_STATE_DIR_BASENAME,
}

export type ProductCliName = typeof ROVE_PRODUCT_NAME | typeof LEGACY_KOBE_PRODUCT_NAME
