import map from './last-modified.json';

/**
 * Last edit date (YYYY-MM-DD) for a docs page, keyed by site path.
 *
 * Generated by scripts/sync-docs.mjs from each source file's git commit date.
 * Returns undefined when the build had no per-file history to read — a shallow
 * clone (Vercel's default) can't distinguish "changed today" from "fetched
 * today", so it emits nothing rather than stamping every page with the build
 * date. Callers must treat a missing date as "unknown", never as "stale".
 */
export function lastModified(path: string): string | undefined {
  return (map as Record<string, string>)[path];
}
